### ISSUE TITLE
check how to remove duplicated argument docs

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#104]
Many functions have arguments X, y, model etc., so currently we're repeating the documentation for those over and over again. Check whether there's a way to avoid that.

**Comment by kallewesterling** [comment]
I don't think that'd be good practice... The points I see made is that hacking docstrings gives the illusion to ease maintenance but often causes more headaches than advantages and also breaks many of the points brought up by the Zen of Python:

> The zen of Python
> 
> Beautiful is better than ugly.
> Explicit is better than implicit.
> Simple is better than complex.
> Complex is better than complicated.
> Flat is better than nested.
> Sparse is better than dense.
> Readability counts.
> …

@mastoffel I'd be happy to check with the ReadTheDocs community, if you'd like?

I have found some hacky ways:
- https://stackoverflow.com/questions/8100166/inheriting-methods-docstrings-in-python
- https://github.com/matplotlib/matplotlib/issues/9414 (rejected in matplotlib)

**Comment by mastoffel** [comment]
Thanks @kallewesterling, I wondered about this. Happy to duplicate docstrings if that's standard and there's no elegant way to avoid it.

**Comment by mastoffel** [comment]
Closing this after @kallewesterling's insights here.
