### ISSUE TITLE
Optimise PyTorch MLP hyperparameter search

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#128]
MLP hyperparameter search is a little tricky as the space includes the architecture (layers etc.). We need to find a good hyperparameter grid subspace that works well with our datasets.

**Comment by kallewesterling** [comment]
@bryanlimy @mastoffel Are there any updates on this issue?

**Comment by bryanlimy** [comment]
I am playing with the hyperparameter grid and able to find a model that achieved >0.89 R**2 on `cardiac1`, but it seems like there is an issue passing `module__` arguments to `TorchModule`. I am debugging it now.

**Comment by bryanlimy** [comment]
https://github.com/alan-turing-institute/autoemulate/pull/157

**Comment by bryanlimy** [comment]
Completed in https://github.com/alan-turing-institute/autoemulate/pull/157
