### ISSUE TITLE
Proper model register

### ISSUE THREAD

**Issue by bryanlimy** [alan-turing-institute/autoemulate#189]
Currently, `MODEL_REGISTER` is a dictionary of emulators where all the emulators would be initialized when we call [`_get_models`](https://github.com/alan-turing-institute/autoemulate/blob/8607f205526c47c18b35325c363e3c7f68ca0667/autoemulate/model_processing.py#L6).
```
MODEL_REGISTRY = {
    "SecondOrderPolynomial": SecondOrderPolynomial(),
    "RBF": RBF(),
    "RandomForest": RandomForest(),
    "GradientBoosting": GradientBoosting(),
    "GaussianProcessSk": GaussianProcessSk(),
    "SupportVectorMachines": SupportVectorMachines(),
    "XGBoost": XGBoost(),
    "NeuralNetSk": NeuralNetSk(),
    "NeuralNetTorch": NeuralNetTorch(module="mlp"),
    # "GaussianProcess": GaussianProcess,
```

Since `MODEL_REGISTER` is a dictionary, it caches the initialized module and would return initialized module instead of returning a new instance of the module when we call `get_models` again. This would lead to unexpected errors (i.e. shape mismatch). 

As a hotfix https://github.com/alan-turing-institute/autoemulate/pull/180/commits/3db7e7e509e29b6072607a204e6f1d115e20a6f0, we added `deepcopy` in `_get_models` upon initialization, but a proper model register that return an instance of a module is needed.

**Comment by mastoffel** [comment]
fixed by #245
