### ISSUE TITLE
Optimise PyTorch MLP

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#192]
Currently, the PyTorch MLP tends to be a bit worse than the scikit-learn MLP on different datasets. Would be good to find out why, e.g. could it be the optimiser (`lbfgs` works well for small datasets but isn't implemented in PyTorch).

**Comment by kallewesterling** [comment]
Any updates on this issue @mastoffel and @bryanlimy? It looks like the only one pending from our sprint planning meeting currently (beside release)!

**Comment by mastoffel** [comment]
@kallewesterling only partially!

**Comment by mastoffel** [comment]
closing as MLP isn't a core emulator anymore.
