### ISSUE TITLE
PyTorch model error with bayes search

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#199]
This currently doesn't work:

```
em = AutoEmulate()
em.setup(X, y,param_search=True, param_search_type="bayes", model_subset=["NNMlp"])
best = em.compare()
```

With this error:
```
Error fitting model NNMlp
Invalid dimension [<class 'torch.optim.adamw.AdamW'>, <class 'torch.optim.sgd.SGD'>]. Read the documentation for supported types
```

I guess that this line:
`"optimizer": [torch.optim.AdamW, torch.optim.SGD],` 
isn't compatible with bayes search at the moment.

**Comment by kallewesterling** [comment]
@mastoffel Is this perhaps something (as a `bug`) that needs to be prioritised before AI UK? If so, could you estimate size of this issue?

**Comment by mastoffel** [comment]
@kallewesterling agree. Size small if it is what I think it is :)

**Comment by bryanlimy** [comment]
resovled in https://github.com/alan-turing-institute/autoemulate/pull/205
