### ISSUE TITLE
CV is not done on the optimised hyper-parameters but on the default

### ISSUE THREAD

**Issue by MaxBalmus** [alan-turing-institute/autoemulate#222]
### Description

In the `compare` method of `autoemulate`, the results of hyperparameter optimisation are not fed into the CV step, rather the default value is used.

### Reproduction steps

```bash
1. When doing the model setup, set `log_to_file` to true.
2. Set `param_search` to true.
3. In autoemulate.log the `Best parameter for model` and `Parameters` (CV) are different.
```

### Version

0.1.0.post1  

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Linux

**Comment by mastoffel** [comment]
fixed in #224
