### ISSUE TITLE
Potential bug:  Documentation links don't work

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/autoemulate#237]
### Description

Hi! The README has a documentation link at the top of a page as well as a link to the API reference in the `documentation` section but neither works for me (I get a 404 error).

### Reproduction steps

```bash
1. Go to README
2. Click on the `documentation` button
```

### Version

latest

**Comment by kallewesterling** [comment]
Hello! I'm out sick today but can have a look when I'm back.

**Comment by radka-j** [comment]
It seems to work now, no idea why I was getting a 404 yesterday 🤷🏻‍♀️

**Comment by mastoffel** [comment]
I had it too, just tried around with a few things, something must have worked 😅
