### ISSUE TITLE
[epic] Improve plotting

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#49]
`plot_results()` currently produces a simple scatterplot the best fold for each model and each fold for a single model

To do:
- [x] #130
    - depending on how many plots to plot (a 3 x 4 panel looks better than a 1 x 12 panel). Should also take an argument to specify this.
- [x] #131
    - (2d y). This will result in many plots so needs a strategy for staying readable, such as taking a subset or pages.
- [x] #132
- [x] #133

**Comment by kallewesterling** [comment]
@mastoffel This issue needs splitting up into pieces that can take us towards the plotting being done as part of the MVP, if that's important for our next three sprints. I'm happy to take a first stab at it, if you'd like.

**Comment by mastoffel** [comment]
> @mastoffel This issue needs splitting up into pieces that can take us towards the plotting being done as part of the MVP, if that's important for our next three sprints. I'm happy to take a first stab at it, if you'd like.

@kallewesterling That would be great. Have changed it slightly and added a task.

**Comment by kallewesterling** [comment]
Thanks @mastoffel! I have separated them out as issues related to this epic now.
