### ISSUE TITLE
Improve search over GP Kernels

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#52]
Kernel hyperparameters are optimised [internally](https://scikit-learn.org/stable/modules/gaussian_process.html#:~:text=The%20hyperparameters%20of%20the%20kernel%20are%20optimized%20during%20fitting%20of,started%20repeatedly%20by%20specifying%20n_restarts_optimizer%20.) by sklearn. However, there might be ways to do a more thorough search over kernels, for example by [combining kernels](https://scikit-learn.org/stable/modules/gaussian_process.html#kernels-for-gaussian-processes). This needs some research.

**Comment by kallewesterling** [comment]
@mastoffel Just to clarify, this is about refactoring existing code?

**Comment by mastoffel** [comment]
> @mastoffel Just to clarify, this is about refactoring existing code?

This was a bit outdated, have re-framed it now.

**Comment by kallewesterling** [comment]
Thanks @mastoffel!

**Comment by mastoffel** [comment]
closed, as addressed in #253
