### ISSUE TITLE
[epic] Choose initial experimental designs

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#6]
Chose a few sampling methods. 

- [X] Latin Hypercube Sampling
- ...

Inspiration:
[smt toolbox](https://smt.readthedocs.io/en/latest/_src_docs/sampling_methods.html)
[Surrogates.jl](https://docs.sciml.ai/Surrogates/stable/samples/)

**Comment by mastoffel** [comment]
Haven't quite decided yet, added a few resources for different methods.

**Comment by kallewesterling** [comment]
@mastoffel Like #3 this might be an ongoing thing -- and I think we now have initial experimental designs, no? This would be a good thing to talk through in tomorrow's sprint planning.

**Comment by mastoffel** [comment]
> @mastoffel Like #3 this might be an ongoing thing -- and I think we now have initial experimental designs, no? This would be a good thing to talk through in tomorrow's sprint planning.

@kallewesterling agree. There's only LHS at the moment, because the user currently has the responsibility for sampling / experimental design, and `autoemulate` only does the model fitting. I don't expect this to change in the near future as it will be very difficult to automate that step.

**Comment by kallewesterling** [comment]
This is a great point to add to the documentation (see #71):

> the user currently has the responsibility for sampling / experimental design, and `autoemulate` only does the model fitting

Otherwise, I think we might want to close down this issue, and then add in something in the contribution guidelines that this is an open and ongoing invitation to add more sampling/experimental design strategies?

**Comment by mastoffel** [comment]
> This is a great point to add to the documentation (see #71):
> 
> > the user currently has the responsibility for sampling / experimental design, and `autoemulate` only does the model fitting
> 

Yes, I'll draft a longer introduction soon, and it'll be in there.

> Otherwise, I think we might want to close down this issue, and then add in something in the contribution guidelines that this is an open and ongoing invitation to add more sampling/experimental design strategies?

Yes, I agree!

**Comment by kallewesterling** [comment]
Sounds great. I'll close the issue but add in these notes in #71.
