### ISSUE TITLE
Second Order Polynomials Singular Matrix error

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#67]
Some of the smt toolbox benchmarks (e.g. `from smt.problems import WaterFlow`) throw a numpy.linalg.LinAlgError: Singular matrix error for the second order polynomial emulator. 

```
import numpy as np
from smt.problems import WaterFlow

ndim = 8
problem = WaterFlow(ndim=ndim)

num = 100
x = np.ones((num, ndim))
for i in range(ndim):
    x[:, i] = 0.5 * (problem.xlimits[i, 0] + problem.xlimits[i, 1])
x[:, 0] = np.linspace(0.05, 0.15, num)
y = problem(x)

em = AutoEmulate()
em.setup(x, y)
em.compare()
```

**Comment by kallewesterling** [comment]
You're on fire today, @mastoffel!!!! I hope you're going to the xmas party and get to relax and have some fun this afternoon :)
