### ISSUE TITLE
`SecondOrderPolynomial()` fails checks

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#81]
fails three of the estimator checks related to 

```
>       assert y_pred.shape == y_.shape
E       AssertionError
```

Reshaping `y_pred` should solve this.

Note: remove `"check_regressors_train"`from `"_xfail_checks"` in estimator tags to run the test.

**Comment by kallewesterling** [comment]
Congratulations! 🚀
