### ISSUE TITLE
add `isort` to pre-commit

### ISSUE THREAD

**Issue by mastoffel** [alan-turing-institute/autoemulate#94]
sorting imports with [isort](https://pycqa.github.io/isort/), thanks to @bryanlimy for the suggestion.

**Comment by kallewesterling** [comment]
Looks pretty [easy to implement](https://pycqa.github.io/isort/docs/configuration/pre-commit.html) - want me to have a quick go, @mastoffel?

**Comment by mastoffel** [comment]
Yes, please!

**Comment by kallewesterling** [comment]
Turns out it wasn't as easy as they made it look! Not giving up yet though!

**Comment by mastoffel** [comment]
ah, it never is! Don't worry too much if it doesn't work @kallewesterling!

**Comment by mastoffel** [comment]
@all-contributors please add @kallewesterling for doc, code, content

**Comment by mastoffel** [comment]
@all-contributors please add @kallewesterling for doc, code, content

**Comment by mastoffel** [comment]
forgot: @all-contributors add projectManagement for @kallewesterling

**Comment by mastoffel** [comment]
sorting pre-commit implemented by @kallewesterling in #114 , using [reorder-python-imports](https://github.com/asottile/reorder-python-imports) as `poetry` made problems with `isort`.

**Comment by mastoffel** [comment]
sorting pre-commit implemented by @kallewesterling in #114 , using [reorder-python-imports](https://github.com/asottile/reorder-python-imports) as `poetry` made problems with `isort`.
